// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/nextphoton/auth-service/ent"
)

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken string    `json:"accessToken"`
	User        *ent.User `json:"user"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type RegisterInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Role     *string `json:"role,omitempty"`
}

type RegisterResponse struct {
	User        *ent.User `json:"user"`
	AccessToken *string   `json:"accessToken,omitempty"`
	Message     string    `json:"message"`
}

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type UserEdge struct {
	Node   *ent.User `json:"node"`
	Cursor string    `json:"cursor"`
}
