// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nextphoton/auth-service/ent/account"
	"github.com/nextphoton/auth-service/ent/predicate"
	"github.com/nextphoton/auth-service/ent/user"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpdate) SetAccountID(v string) *AccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccountID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AccountUpdate) SetProviderID(v string) *AccountUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableProviderID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUpdate) SetUserID(v string) *AccountUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUserID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *AccountUpdate) SetAccessToken(v string) *AccountUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccessToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *AccountUpdate) ClearAccessToken() *AccountUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AccountUpdate) SetRefreshToken(v string) *AccountUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableRefreshToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *AccountUpdate) ClearRefreshToken() *AccountUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetIDToken sets the "id_token" field.
func (_u *AccountUpdate) SetIDToken(v string) *AccountUpdate {
	_u.mutation.SetIDToken(v)
	return _u
}

// SetNillableIDToken sets the "id_token" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIDToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetIDToken(*v)
	}
	return _u
}

// ClearIDToken clears the value of the "id_token" field.
func (_u *AccountUpdate) ClearIDToken() *AccountUpdate {
	_u.mutation.ClearIDToken()
	return _u
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_u *AccountUpdate) SetAccessTokenExpiresAt(v time.Time) *AccountUpdate {
	_u.mutation.SetAccessTokenExpiresAt(v)
	return _u
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccessTokenExpiresAt(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetAccessTokenExpiresAt(*v)
	}
	return _u
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (_u *AccountUpdate) ClearAccessTokenExpiresAt() *AccountUpdate {
	_u.mutation.ClearAccessTokenExpiresAt()
	return _u
}

// SetRefreshTokenExpiresAt sets the "refresh_token_expires_at" field.
func (_u *AccountUpdate) SetRefreshTokenExpiresAt(v time.Time) *AccountUpdate {
	_u.mutation.SetRefreshTokenExpiresAt(v)
	return _u
}

// SetNillableRefreshTokenExpiresAt sets the "refresh_token_expires_at" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableRefreshTokenExpiresAt(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetRefreshTokenExpiresAt(*v)
	}
	return _u
}

// ClearRefreshTokenExpiresAt clears the value of the "refresh_token_expires_at" field.
func (_u *AccountUpdate) ClearRefreshTokenExpiresAt() *AccountUpdate {
	_u.mutation.ClearRefreshTokenExpiresAt()
	return _u
}

// SetScope sets the "scope" field.
func (_u *AccountUpdate) SetScope(v string) *AccountUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableScope(v *string) *AccountUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *AccountUpdate) ClearScope() *AccountUpdate {
	_u.mutation.ClearScope()
	return _u
}

// SetPassword sets the "password" field.
func (_u *AccountUpdate) SetPassword(v string) *AccountUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *AccountUpdate) SetNillablePassword(v *string) *AccountUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *AccountUpdate) ClearPassword() *AccountUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUpdatedAt(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AccountUpdate) ClearUpdatedAt() *AccountUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdate) SetUser(v *User) *AccountUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdate) ClearUser() *AccountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := account.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Account.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := account.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Account.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := account.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Account.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(account.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(account.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(account.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(account.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(account.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.IDToken(); ok {
		_spec.SetField(account.FieldIDToken, field.TypeString, value)
	}
	if _u.mutation.IDTokenCleared() {
		_spec.ClearField(account.FieldIDToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(account.FieldAccessTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AccessTokenExpiresAtCleared() {
		_spec.ClearField(account.FieldAccessTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshTokenExpiresAt(); ok {
		_spec.SetField(account.FieldRefreshTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshTokenExpiresAtCleared() {
		_spec.ClearField(account.FieldRefreshTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(account.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(account.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(account.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(account.FieldPassword, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(account.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(account.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpdateOne) SetAccountID(v string) *AccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccountID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AccountUpdateOne) SetProviderID(v string) *AccountUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableProviderID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountUpdateOne) SetUserID(v string) *AccountUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUserID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *AccountUpdateOne) SetAccessToken(v string) *AccountUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccessToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *AccountUpdateOne) ClearAccessToken() *AccountUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AccountUpdateOne) SetRefreshToken(v string) *AccountUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableRefreshToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *AccountUpdateOne) ClearRefreshToken() *AccountUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetIDToken sets the "id_token" field.
func (_u *AccountUpdateOne) SetIDToken(v string) *AccountUpdateOne {
	_u.mutation.SetIDToken(v)
	return _u
}

// SetNillableIDToken sets the "id_token" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIDToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetIDToken(*v)
	}
	return _u
}

// ClearIDToken clears the value of the "id_token" field.
func (_u *AccountUpdateOne) ClearIDToken() *AccountUpdateOne {
	_u.mutation.ClearIDToken()
	return _u
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_u *AccountUpdateOne) SetAccessTokenExpiresAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetAccessTokenExpiresAt(v)
	return _u
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccessTokenExpiresAt(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetAccessTokenExpiresAt(*v)
	}
	return _u
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (_u *AccountUpdateOne) ClearAccessTokenExpiresAt() *AccountUpdateOne {
	_u.mutation.ClearAccessTokenExpiresAt()
	return _u
}

// SetRefreshTokenExpiresAt sets the "refresh_token_expires_at" field.
func (_u *AccountUpdateOne) SetRefreshTokenExpiresAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetRefreshTokenExpiresAt(v)
	return _u
}

// SetNillableRefreshTokenExpiresAt sets the "refresh_token_expires_at" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableRefreshTokenExpiresAt(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetRefreshTokenExpiresAt(*v)
	}
	return _u
}

// ClearRefreshTokenExpiresAt clears the value of the "refresh_token_expires_at" field.
func (_u *AccountUpdateOne) ClearRefreshTokenExpiresAt() *AccountUpdateOne {
	_u.mutation.ClearRefreshTokenExpiresAt()
	return _u
}

// SetScope sets the "scope" field.
func (_u *AccountUpdateOne) SetScope(v string) *AccountUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableScope(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *AccountUpdateOne) ClearScope() *AccountUpdateOne {
	_u.mutation.ClearScope()
	return _u
}

// SetPassword sets the "password" field.
func (_u *AccountUpdateOne) SetPassword(v string) *AccountUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillablePassword(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *AccountUpdateOne) ClearPassword() *AccountUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUpdatedAt(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AccountUpdateOne) ClearUpdatedAt() *AccountUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdateOne) SetUser(v *User) *AccountUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdateOne) ClearUser() *AccountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := account.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Account.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := account.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Account.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := account.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Account.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(account.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(account.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(account.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(account.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(account.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.IDToken(); ok {
		_spec.SetField(account.FieldIDToken, field.TypeString, value)
	}
	if _u.mutation.IDTokenCleared() {
		_spec.ClearField(account.FieldIDToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(account.FieldAccessTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AccessTokenExpiresAtCleared() {
		_spec.ClearField(account.FieldAccessTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshTokenExpiresAt(); ok {
		_spec.SetField(account.FieldRefreshTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshTokenExpiresAtCleared() {
		_spec.ClearField(account.FieldRefreshTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(account.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(account.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(account.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(account.FieldPassword, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(account.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(account.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
