// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nextphoton/auth-service/ent/account"
	"github.com/nextphoton/auth-service/ent/user"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (_c *AccountCreate) SetAccountID(v string) *AccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AccountCreate) SetProviderID(v string) *AccountCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountCreate) SetUserID(v string) *AccountCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *AccountCreate) SetAccessToken(v string) *AccountCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *AccountCreate) SetNillableAccessToken(v *string) *AccountCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *AccountCreate) SetRefreshToken(v string) *AccountCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *AccountCreate) SetNillableRefreshToken(v *string) *AccountCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetIDToken sets the "id_token" field.
func (_c *AccountCreate) SetIDToken(v string) *AccountCreate {
	_c.mutation.SetIDToken(v)
	return _c
}

// SetNillableIDToken sets the "id_token" field if the given value is not nil.
func (_c *AccountCreate) SetNillableIDToken(v *string) *AccountCreate {
	if v != nil {
		_c.SetIDToken(*v)
	}
	return _c
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_c *AccountCreate) SetAccessTokenExpiresAt(v time.Time) *AccountCreate {
	_c.mutation.SetAccessTokenExpiresAt(v)
	return _c
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableAccessTokenExpiresAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetAccessTokenExpiresAt(*v)
	}
	return _c
}

// SetRefreshTokenExpiresAt sets the "refresh_token_expires_at" field.
func (_c *AccountCreate) SetRefreshTokenExpiresAt(v time.Time) *AccountCreate {
	_c.mutation.SetRefreshTokenExpiresAt(v)
	return _c
}

// SetNillableRefreshTokenExpiresAt sets the "refresh_token_expires_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableRefreshTokenExpiresAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetRefreshTokenExpiresAt(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *AccountCreate) SetScope(v string) *AccountCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *AccountCreate) SetNillableScope(v *string) *AccountCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *AccountCreate) SetPassword(v string) *AccountCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *AccountCreate) SetNillablePassword(v *string) *AccountCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCreate) SetUpdatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v string) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountCreate) SetUser(v *User) *AccountCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Account.account_id"`)}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := account.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Account.account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "Account.provider_id"`)}
	}
	if v, ok := _c.mutation.ProviderID(); ok {
		if err := account.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "Account.provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Account.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := account.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Account.user_id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Account.user"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Account.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(account.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(account.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = &value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(account.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = &value
	}
	if value, ok := _c.mutation.IDToken(); ok {
		_spec.SetField(account.FieldIDToken, field.TypeString, value)
		_node.IDToken = &value
	}
	if value, ok := _c.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(account.FieldAccessTokenExpiresAt, field.TypeTime, value)
		_node.AccessTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.RefreshTokenExpiresAt(); ok {
		_spec.SetField(account.FieldRefreshTokenExpiresAt, field.TypeTime, value)
		_node.RefreshTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(account.FieldScope, field.TypeString, value)
		_node.Scope = &value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(account.FieldPassword, field.TypeString, value)
		_node.Password = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
