// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/nextphoton/auth-service/ent/account"
	"github.com/nextphoton/auth-service/ent/permission"
	"github.com/nextphoton/auth-service/ent/role"
	"github.com/nextphoton/auth-service/ent/rolepermission"
	"github.com/nextphoton/auth-service/ent/schema"
	"github.com/nextphoton/auth-service/ent/session"
	"github.com/nextphoton/auth-service/ent/user"
	"github.com/nextphoton/auth-service/ent/userpermission"
	"github.com/nextphoton/auth-service/ent/userrole"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescAccountID is the schema descriptor for account_id field.
	accountDescAccountID := accountFields[1].Descriptor()
	// account.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	account.AccountIDValidator = accountDescAccountID.Validators[0].(func(string) error)
	// accountDescProviderID is the schema descriptor for provider_id field.
	accountDescProviderID := accountFields[2].Descriptor()
	// account.ProviderIDValidator is a validator for the "provider_id" field. It is called by the builders before save.
	account.ProviderIDValidator = accountDescProviderID.Validators[0].(func(string) error)
	// accountDescUserID is the schema descriptor for user_id field.
	accountDescUserID := accountFields[3].Descriptor()
	// account.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	account.UserIDValidator = accountDescUserID.Validators[0].(func(string) error)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescResource is the schema descriptor for resource field.
	permissionDescResource := permissionFields[1].Descriptor()
	// permission.ResourceValidator is a validator for the "resource" field. It is called by the builders before save.
	permission.ResourceValidator = permissionDescResource.Validators[0].(func(string) error)
	// permissionDescAction is the schema descriptor for action field.
	permissionDescAction := permissionFields[2].Descriptor()
	// permission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permission.ActionValidator = permissionDescAction.Validators[0].(func(string) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescIsActive is the schema descriptor for is_active field.
	roleDescIsActive := roleFields[4].Descriptor()
	// role.DefaultIsActive holds the default value on creation for the is_active field.
	role.DefaultIsActive = roleDescIsActive.Default.(bool)
	// roleDescIsDefault is the schema descriptor for is_default field.
	roleDescIsDefault := roleFields[5].Descriptor()
	// role.DefaultIsDefault holds the default value on creation for the is_default field.
	role.DefaultIsDefault = roleDescIsDefault.Default.(bool)
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescRoleID is the schema descriptor for role_id field.
	rolepermissionDescRoleID := rolepermissionFields[1].Descriptor()
	// rolepermission.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	rolepermission.RoleIDValidator = rolepermissionDescRoleID.Validators[0].(func(string) error)
	// rolepermissionDescPermissionID is the schema descriptor for permission_id field.
	rolepermissionDescPermissionID := rolepermissionFields[2].Descriptor()
	// rolepermission.PermissionIDValidator is a validator for the "permission_id" field. It is called by the builders before save.
	rolepermission.PermissionIDValidator = rolepermissionDescPermissionID.Validators[0].(func(string) error)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[2].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[7].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[3].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	userpermissionFields := schema.UserPermission{}.Fields()
	_ = userpermissionFields
	// userpermissionDescUserID is the schema descriptor for user_id field.
	userpermissionDescUserID := userpermissionFields[1].Descriptor()
	// userpermission.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userpermission.UserIDValidator = userpermissionDescUserID.Validators[0].(func(string) error)
	// userpermissionDescPermissionID is the schema descriptor for permission_id field.
	userpermissionDescPermissionID := userpermissionFields[2].Descriptor()
	// userpermission.PermissionIDValidator is a validator for the "permission_id" field. It is called by the builders before save.
	userpermission.PermissionIDValidator = userpermissionDescPermissionID.Validators[0].(func(string) error)
	// userpermissionDescOverrideType is the schema descriptor for override_type field.
	userpermissionDescOverrideType := userpermissionFields[3].Descriptor()
	// userpermission.OverrideTypeValidator is a validator for the "override_type" field. It is called by the builders before save.
	userpermission.OverrideTypeValidator = userpermissionDescOverrideType.Validators[0].(func(string) error)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescUserID is the schema descriptor for user_id field.
	userroleDescUserID := userroleFields[1].Descriptor()
	// userrole.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userrole.UserIDValidator = userroleDescUserID.Validators[0].(func(string) error)
	// userroleDescRoleID is the schema descriptor for role_id field.
	userroleDescRoleID := userroleFields[2].Descriptor()
	// userrole.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	userrole.RoleIDValidator = userroleDescRoleID.Validators[0].(func(string) error)
	// userroleDescIsActive is the schema descriptor for is_active field.
	userroleDescIsActive := userroleFields[5].Descriptor()
	// userrole.DefaultIsActive holds the default value on creation for the is_active field.
	userrole.DefaultIsActive = userroleDescIsActive.Default.(bool)
}
