// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nextphoton/auth-service/ent/permission"
	"github.com/nextphoton/auth-service/ent/user"
	"github.com/nextphoton/auth-service/ent/userpermission"
)

// UserPermission is the model entity for the UserPermission schema.
type UserPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID string `json:"permission_id,omitempty"`
	// grant or deny
	OverrideType string `json:"override_type,omitempty"`
	// Constraints holds the value of the "constraints" field.
	Constraints map[string]interface{} `json:"constraints,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *string `json:"organization_id,omitempty"`
	// GrantedBy holds the value of the "granted_by" field.
	GrantedBy *string `json:"granted_by,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt *time.Time `json:"granted_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserPermissionQuery when eager-loading is set.
	Edges        UserPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserPermissionEdges holds the relations/edges for other nodes in the graph.
type UserPermissionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Permission holds the value of the permission edge.
	Permission *Permission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPermissionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPermissionEdges) PermissionOrErr() (*Permission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: permission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldConstraints:
			values[i] = new([]byte)
		case userpermission.FieldID, userpermission.FieldUserID, userpermission.FieldPermissionID, userpermission.FieldOverrideType, userpermission.FieldOrganizationID, userpermission.FieldGrantedBy, userpermission.FieldReason:
			values[i] = new(sql.NullString)
		case userpermission.FieldGrantedAt, userpermission.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPermission fields.
func (_m *UserPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case userpermission.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case userpermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = value.String
			}
		case userpermission.FieldOverrideType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field override_type", values[i])
			} else if value.Valid {
				_m.OverrideType = value.String
			}
		case userpermission.FieldConstraints:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field constraints", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Constraints); err != nil {
					return fmt.Errorf("unmarshal field constraints: %w", err)
				}
			}
		case userpermission.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(string)
				*_m.OrganizationID = value.String
			}
		case userpermission.FieldGrantedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by", values[i])
			} else if value.Valid {
				_m.GrantedBy = new(string)
				*_m.GrantedBy = value.String
			}
		case userpermission.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = new(time.Time)
				*_m.GrantedAt = value.Time
			}
		case userpermission.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case userpermission.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPermission.
// This includes values selected through modifiers, order, etc.
func (_m *UserPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserPermission entity.
func (_m *UserPermission) QueryUser() *UserQuery {
	return NewUserPermissionClient(_m.config).QueryUser(_m)
}

// QueryPermission queries the "permission" edge of the UserPermission entity.
func (_m *UserPermission) QueryPermission() *PermissionQuery {
	return NewUserPermissionClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this UserPermission.
// Note that you need to call UserPermission.Unwrap() before calling this method if this UserPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPermission) Update() *UserPermissionUpdateOne {
	return NewUserPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPermission) Unwrap() *UserPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPermission) String() string {
	var builder strings.Builder
	builder.WriteString("UserPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(_m.PermissionID)
	builder.WriteString(", ")
	builder.WriteString("override_type=")
	builder.WriteString(_m.OverrideType)
	builder.WriteString(", ")
	builder.WriteString("constraints=")
	builder.WriteString(fmt.Sprintf("%v", _m.Constraints))
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GrantedBy; v != nil {
		builder.WriteString("granted_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GrantedAt; v != nil {
		builder.WriteString("granted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserPermissions is a parsable slice of UserPermission.
type UserPermissions []*UserPermission
