// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nextphoton/auth-service/ent/permission"
	"github.com/nextphoton/auth-service/ent/user"
	"github.com/nextphoton/auth-service/ent/userpermission"
)

// UserPermissionCreate is the builder for creating a UserPermission entity.
type UserPermissionCreate struct {
	config
	mutation *UserPermissionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserPermissionCreate) SetUserID(v string) *UserPermissionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *UserPermissionCreate) SetPermissionID(v string) *UserPermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetOverrideType sets the "override_type" field.
func (_c *UserPermissionCreate) SetOverrideType(v string) *UserPermissionCreate {
	_c.mutation.SetOverrideType(v)
	return _c
}

// SetConstraints sets the "constraints" field.
func (_c *UserPermissionCreate) SetConstraints(v map[string]interface{}) *UserPermissionCreate {
	_c.mutation.SetConstraints(v)
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *UserPermissionCreate) SetOrganizationID(v string) *UserPermissionCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableOrganizationID(v *string) *UserPermissionCreate {
	if v != nil {
		_c.SetOrganizationID(*v)
	}
	return _c
}

// SetGrantedBy sets the "granted_by" field.
func (_c *UserPermissionCreate) SetGrantedBy(v string) *UserPermissionCreate {
	_c.mutation.SetGrantedBy(v)
	return _c
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableGrantedBy(v *string) *UserPermissionCreate {
	if v != nil {
		_c.SetGrantedBy(*v)
	}
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *UserPermissionCreate) SetGrantedAt(v time.Time) *UserPermissionCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableGrantedAt(v *time.Time) *UserPermissionCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserPermissionCreate) SetExpiresAt(v time.Time) *UserPermissionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableExpiresAt(v *time.Time) *UserPermissionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *UserPermissionCreate) SetReason(v string) *UserPermissionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *UserPermissionCreate) SetNillableReason(v *string) *UserPermissionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserPermissionCreate) SetID(v string) *UserPermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPermissionCreate) SetUser(v *User) *UserPermissionCreate {
	return _c.SetUserID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_c *UserPermissionCreate) SetPermission(v *Permission) *UserPermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// Mutation returns the UserPermissionMutation object of the builder.
func (_c *UserPermissionCreate) Mutation() *UserPermissionMutation {
	return _c.mutation
}

// Save creates the UserPermission in the database.
func (_c *UserPermissionCreate) Save(ctx context.Context) (*UserPermission, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPermissionCreate) SaveX(ctx context.Context) *UserPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPermissionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPermission.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userpermission.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserPermission.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "UserPermission.permission_id"`)}
	}
	if v, ok := _c.mutation.PermissionID(); ok {
		if err := userpermission.PermissionIDValidator(v); err != nil {
			return &ValidationError{Name: "permission_id", err: fmt.Errorf(`ent: validator failed for field "UserPermission.permission_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OverrideType(); !ok {
		return &ValidationError{Name: "override_type", err: errors.New(`ent: missing required field "UserPermission.override_type"`)}
	}
	if v, ok := _c.mutation.OverrideType(); ok {
		if err := userpermission.OverrideTypeValidator(v); err != nil {
			return &ValidationError{Name: "override_type", err: fmt.Errorf(`ent: validator failed for field "UserPermission.override_type": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPermission.user"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "UserPermission.permission"`)}
	}
	return nil
}

func (_c *UserPermissionCreate) sqlSave(ctx context.Context) (*UserPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserPermission.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPermissionCreate) createSpec() (*UserPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpermission.Table, sqlgraph.NewFieldSpec(userpermission.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OverrideType(); ok {
		_spec.SetField(userpermission.FieldOverrideType, field.TypeString, value)
		_node.OverrideType = value
	}
	if value, ok := _c.mutation.Constraints(); ok {
		_spec.SetField(userpermission.FieldConstraints, field.TypeJSON, value)
		_node.Constraints = value
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(userpermission.FieldOrganizationID, field.TypeString, value)
		_node.OrganizationID = &value
	}
	if value, ok := _c.mutation.GrantedBy(); ok {
		_spec.SetField(userpermission.FieldGrantedBy, field.TypeString, value)
		_node.GrantedBy = &value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(userpermission.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userpermission.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(userpermission.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPermissionCreateBulk is the builder for creating many UserPermission entities in bulk.
type UserPermissionCreateBulk struct {
	config
	err      error
	builders []*UserPermissionCreate
}

// Save creates the UserPermission entities in the database.
func (_c *UserPermissionCreateBulk) Save(ctx context.Context) ([]*UserPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPermissionCreateBulk) SaveX(ctx context.Context) []*UserPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
