# =============================================================================
# NextPhoton EduCare Platform - Root Terragrunt Configuration
# =============================================================================
# This is the root Terragrunt configuration file that provides common settings
# for all environments. Individual environments inherit and can override these.
# =============================================================================

# -----------------------------------------------------------------------------
# Local Variables
# Common values used across all environments
# -----------------------------------------------------------------------------
locals {
  # Project-wide settings
  project_name = "nextphoton"
  org_name     = "nextphoton-educare"

  # Default region (can be overridden per environment)
  default_region = "us-central1"

  # Parse the environment from the path
  # Expected path structure: environments/{env}/terragrunt.hcl
  path_parts  = split("/", path_relative_to_include())
  environment = try(local.path_parts[1], "dev")

  # Common tags applied to all resources
  common_tags = {
    Project     = local.project_name
    ManagedBy   = "terraform"
    Repository  = "github.com/nextphoton/nextphoton"
    Environment = local.environment
    Team        = "platform"
  }

  # State bucket naming convention
  state_bucket_prefix = "${local.project_name}-terraform-state"
}

# -----------------------------------------------------------------------------
# Remote State Configuration
# Using Google Cloud Storage for state management
# Alternative: AWS S3 + DynamoDB (configuration included but commented)
# -----------------------------------------------------------------------------
remote_state {
  backend = "gcs"

  config = {
    # State bucket - one per environment for isolation
    bucket = "${local.state_bucket_prefix}-${local.environment}"

    # State file path within the bucket
    prefix = "${path_relative_to_include()}/terraform.tfstate"

    # GCP project for the state bucket
    project = "${local.project_name}-${local.environment}"

    # Bucket location
    location = "US"

    # Enable versioning for state file recovery
    enable_bucket_policy_only = true
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# Alternative: AWS S3 Backend Configuration
# Uncomment below and comment GCS config above to use AWS
# remote_state {
#   backend = "s3"
#
#   config = {
#     bucket         = "${local.state_bucket_prefix}-${local.environment}"
#     key            = "${path_relative_to_include()}/terraform.tfstate"
#     region         = "us-east-1"
#     encrypt        = true
#     dynamodb_table = "${local.project_name}-terraform-locks"
#
#     # Enable versioning
#     versioning = true
#   }
#
#   generate = {
#     path      = "backend.tf"
#     if_exists = "overwrite_terragrunt"
#   }
# }

# -----------------------------------------------------------------------------
# Provider Generation
# Generates provider configuration for all child modules
# -----------------------------------------------------------------------------
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<EOF
# =============================================================================
# Auto-generated by Terragrunt - DO NOT EDIT
# =============================================================================

# Google Cloud Provider
provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
}

provider "google-beta" {
  project = var.gcp_project_id
  region  = var.gcp_region
}

# AWS Provider (for multi-cloud or AWS-primary deployments)
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = var.common_tags
  }
}

# Kubernetes Provider - configured after cluster creation
provider "kubernetes" {
  host                   = var.kubernetes_host
  cluster_ca_certificate = base64decode(var.kubernetes_ca_cert)
  token                  = var.kubernetes_token
}

# Helm Provider
provider "helm" {
  kubernetes {
    host                   = var.kubernetes_host
    cluster_ca_certificate = base64decode(var.kubernetes_ca_cert)
    token                  = var.kubernetes_token
  }
}

# Cloudflare Provider
provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# NeonDB Provider
provider "neon" {
  api_key = var.neon_api_key
}

# Vault Provider
provider "vault" {
  address = var.vault_address
  token   = var.vault_token
}
EOF
}

# -----------------------------------------------------------------------------
# Common Variables Generation
# Generates common variable definitions for all child modules
# -----------------------------------------------------------------------------
generate "common_variables" {
  path      = "common_variables.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<EOF
# =============================================================================
# Auto-generated by Terragrunt - DO NOT EDIT
# =============================================================================

variable "gcp_project_id" {
  description = "GCP project ID"
  type        = string
}

variable "gcp_region" {
  description = "GCP region"
  type        = string
  default     = "us-central1"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
}

variable "common_tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default     = {}
}

variable "kubernetes_host" {
  description = "Kubernetes cluster endpoint"
  type        = string
  default     = ""
}

variable "kubernetes_ca_cert" {
  description = "Kubernetes cluster CA certificate (base64)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "kubernetes_token" {
  description = "Kubernetes authentication token"
  type        = string
  default     = ""
  sensitive   = true
}

variable "cloudflare_api_token" {
  description = "Cloudflare API token"
  type        = string
  default     = ""
  sensitive   = true
}

variable "neon_api_key" {
  description = "NeonDB API key"
  type        = string
  default     = ""
  sensitive   = true
}

variable "vault_address" {
  description = "HashiCorp Vault server address"
  type        = string
  default     = ""
}

variable "vault_token" {
  description = "HashiCorp Vault authentication token"
  type        = string
  default     = ""
  sensitive   = true
}
EOF
}

# -----------------------------------------------------------------------------
# Common Inputs
# These values are passed to all child modules
# -----------------------------------------------------------------------------
inputs = {
  project_name = local.project_name
  environment  = local.environment
  common_tags  = local.common_tags
  gcp_region   = local.default_region
}

# -----------------------------------------------------------------------------
# Terraform Configuration
# Common Terraform settings for all environments
# -----------------------------------------------------------------------------
terraform {
  # Extra arguments for terraform init
  extra_arguments "init_args" {
    commands = ["init"]

    arguments = [
      "-upgrade",
      "-reconfigure",
    ]
  }

  # Extra arguments for terraform plan/apply
  extra_arguments "common_vars" {
    commands = get_terraform_commands_that_need_vars()

    # Load common tfvars file if it exists
    optional_var_files = [
      "${get_parent_terragrunt_dir()}/common.tfvars",
    ]
  }

  # Retry configuration for transient failures
  extra_arguments "retry_lock" {
    commands  = get_terraform_commands_that_need_locking()
    arguments = ["-lock-timeout=20m"]
  }
}

# -----------------------------------------------------------------------------
# Hooks
# Pre and post hooks for terraform operations
# -----------------------------------------------------------------------------
terraform {
  before_hook "validate_environment" {
    commands = ["plan", "apply", "destroy"]
    execute  = ["echo", "Running Terraform for environment: ${local.environment}"]
  }

  after_hook "cleanup_cache" {
    commands     = ["apply", "destroy"]
    execute      = ["rm", "-rf", ".terraform/modules"]
    run_on_error = true
  }
}

# -----------------------------------------------------------------------------
# Skip Protection
# Prevent accidental destruction of critical resources
# -----------------------------------------------------------------------------
prevent_destroy = false  # Override in prod environment

# -----------------------------------------------------------------------------
# Dependency Configuration
# Define module dependency ordering
# -----------------------------------------------------------------------------
# Note: Individual modules should use dependency blocks to define their
# specific dependencies. This ensures proper creation/destruction order.
