// classSessionsDummyData.ts

export type ClassSession = {
    id: string;
    title: string;
    educatorId: string;
    educatorName?: string;
    classId: string;
    batchName?: string;
    subject?: string;
    scheduledAt: string; // ISO string
    durationMinutes: number;
    meetingLink: string;
    recordingUrl?: string;
    status: "scheduled" | "live" | "completed" | "cancelled";
    topicsCovered?: string[];
    learnersPresent?: string[]; // learner IDs
    enrolledStudents?: number;
    notes?: string;
    createdBy: string; // Admin or Educator ID
};

const classSessions: ClassSession[] = [
    {
        id: "cs001",
        title: "Mechanics - Newton's Laws Advanced Problems",
        educatorId: "e001",
        educatorName: "Dr. Meera Sharma",
        classId: "batch_jee_2026_01",
        batchName: "JEE 2026 Advanced Batch",
        subject: "Physics",
        scheduledAt: "2024-03-25T10:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs001",
        status: "scheduled",
        topicsCovered: ["Newton's Laws", "Friction", "Circular Motion"],
        enrolledStudents: 45,
        notes: "Focus on JEE Advanced level problems",
        createdBy: "admin001",
    },
    {
        id: "cs002",
        title: "Organic Chemistry - Reaction Mechanisms",
        educatorId: "e002",
        educatorName: "Prof. Anand Iyer",
        classId: "batch_neet_2025_01",
        batchName: "NEET 2025 Foundation",
        subject: "Chemistry",
        scheduledAt: "2024-03-25T08:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs002",
        status: "scheduled",
        topicsCovered: ["SN1/SN2 Reactions", "Elimination Reactions", "Rearrangements"],
        enrolledStudents: 38,
        notes: "Interactive session with 3D molecular models",
        createdBy: "admin001",
    },
    {
        id: "cs003",
        title: "Quadratic Equations - Problem Solving",
        educatorId: "e004",
        educatorName: "Mr. Ramesh Kulkarni",
        classId: "batch_10th_cbse_01",
        batchName: "10th CBSE Board Prep",
        subject: "Mathematics",
        scheduledAt: "2024-03-24T13:30:00.000Z",
        durationMinutes: 60,
        meetingLink: "https://meet.nextphoton.com/session/cs003",
        recordingUrl: "https://recordings.nextphoton.com/cs003.mp4",
        status: "completed",
        topicsCovered: ["Quadratic Formula", "Factorization", "Word Problems"],
        learnersPresent: ["l001", "l002", "l003", "l006"],
        enrolledStudents: 32,
        notes: "28 students attended. Good engagement with practice problems.",
        createdBy: "admin001",
    },
    {
        id: "cs004",
        title: "Human Physiology - Respiratory System",
        educatorId: "e003",
        educatorName: "Dr. Priya Nair",
        classId: "batch_neet_2025_01",
        batchName: "NEET 2025 Foundation",
        subject: "Biology",
        scheduledAt: "2024-03-26T04:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs004",
        status: "scheduled",
        topicsCovered: ["Gas Exchange", "Transport of O2 and CO2", "Regulation of Breathing"],
        enrolledStudents: 42,
        notes: "NCERT based content with NEET focus",
        createdBy: "admin002",
    },
    {
        id: "cs005",
        title: "Essay Writing Skills",
        educatorId: "e006",
        educatorName: "Ms. Kavita Menon",
        classId: "batch_8th_cbse_01",
        batchName: "8th CBSE Regular",
        subject: "English",
        scheduledAt: "2024-03-23T09:30:00.000Z",
        durationMinutes: 90,
        meetingLink: "https://meet.nextphoton.com/session/cs005",
        recordingUrl: "https://recordings.nextphoton.com/cs005.mp4",
        status: "completed",
        topicsCovered: ["Essay Structure", "Introduction Writing", "Conclusion Techniques"],
        learnersPresent: ["l004", "l007", "l008"],
        enrolledStudents: 25,
        notes: "22 students attended. Excellent participation in workshop activities.",
        createdBy: "admin002",
    },
    {
        id: "cs006",
        title: "Electrostatics - Coulomb's Law Applications",
        educatorId: "e001",
        educatorName: "Dr. Meera Sharma",
        classId: "batch_jee_2026_01",
        batchName: "JEE 2026 Advanced Batch",
        subject: "Physics",
        scheduledAt: "2024-03-27T10:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs006",
        status: "scheduled",
        topicsCovered: ["Coulomb's Law", "Electric Field", "Gauss's Law"],
        enrolledStudents: 45,
        createdBy: "admin001",
    },
    {
        id: "cs007",
        title: "Calculus - Integration Techniques",
        educatorId: "e004",
        educatorName: "Mr. Ramesh Kulkarni",
        classId: "batch_jee_2026_01",
        batchName: "JEE 2026 Advanced Batch",
        subject: "Mathematics",
        scheduledAt: "2024-03-28T12:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs007",
        status: "scheduled",
        topicsCovered: ["Integration by Parts", "Substitution Method", "Partial Fractions"],
        enrolledStudents: 43,
        notes: "Problem solving session with JEE focus",
        createdBy: "admin001",
    },
    {
        id: "cs008",
        title: "Indian Independence Movement",
        educatorId: "e005",
        educatorName: "Prof. Sanjay Gupta",
        classId: "batch_12th_humanities_01",
        batchName: "12th Humanities",
        subject: "History",
        scheduledAt: "2024-03-22T05:30:00.000Z",
        durationMinutes: 90,
        meetingLink: "https://meet.nextphoton.com/session/cs008",
        recordingUrl: "https://recordings.nextphoton.com/cs008.mp4",
        status: "completed",
        topicsCovered: ["Quit India Movement", "Role of Gandhi", "Partition"],
        learnersPresent: ["l005"],
        enrolledStudents: 28,
        notes: "25 students attended. Good discussion on historical events.",
        createdBy: "admin002",
    },
    {
        id: "cs009",
        title: "Physical Chemistry - Thermodynamics",
        educatorId: "e002",
        educatorName: "Prof. Anand Iyer",
        classId: "batch_jee_2026_01",
        batchName: "JEE 2026 Advanced Batch",
        subject: "Chemistry",
        scheduledAt: "2024-03-29T08:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs009",
        status: "scheduled",
        topicsCovered: ["First Law", "Enthalpy", "Hess's Law"],
        enrolledStudents: 44,
        createdBy: "admin001",
    },
    {
        id: "cs010",
        title: "Life Processes - Nutrition",
        educatorId: "e003",
        educatorName: "Dr. Priya Nair",
        classId: "batch_10th_cbse_01",
        batchName: "10th CBSE Board Prep",
        subject: "Biology",
        scheduledAt: "2024-03-21T11:30:00.000Z",
        durationMinutes: 60,
        meetingLink: "https://meet.nextphoton.com/session/cs010",
        recordingUrl: "https://recordings.nextphoton.com/cs010.mp4",
        status: "completed",
        topicsCovered: ["Autotrophic Nutrition", "Heterotrophic Nutrition", "Human Digestive System"],
        learnersPresent: ["l003", "l006"],
        enrolledStudents: 35,
        notes: "32 students attended. Revision class for board exam.",
        createdBy: "admin002",
    },
    {
        id: "cs011",
        title: "Python Programming - Functions and Modules",
        educatorId: "e007",
        educatorName: "Mr. Arun Kumar",
        classId: "batch_11th_cs_01",
        batchName: "11th Computer Science",
        subject: "Computer Science",
        scheduledAt: "2024-03-30T04:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs011",
        status: "scheduled",
        topicsCovered: ["Function Definition", "Parameters", "Modules", "Packages"],
        enrolledStudents: 30,
        notes: "Practical lab session with coding exercises",
        createdBy: "admin003",
    },
    {
        id: "cs012",
        title: "Physical Geography - Climate and Weather",
        educatorId: "e008",
        educatorName: "Ms. Neha Singh",
        classId: "batch_9th_cbse_01",
        batchName: "9th CBSE Regular",
        subject: "Geography",
        scheduledAt: "2024-03-20T08:30:00.000Z",
        durationMinutes: 90,
        meetingLink: "https://meet.nextphoton.com/session/cs012",
        recordingUrl: "https://recordings.nextphoton.com/cs012.mp4",
        status: "completed",
        topicsCovered: ["Atmospheric Pressure", "Wind Systems", "Monsoons"],
        learnersPresent: ["l007"],
        enrolledStudents: 33,
        notes: "30 students attended. Interactive session with weather maps.",
        createdBy: "admin002",
    },
    {
        id: "cs013",
        title: "Modern Physics - Photoelectric Effect",
        educatorId: "e009",
        educatorName: "Dr. Vikram Reddy",
        classId: "batch_neet_2025_01",
        batchName: "NEET 2025 Foundation",
        subject: "Physics",
        scheduledAt: "2024-03-31T10:30:00.000Z",
        durationMinutes: 90,
        meetingLink: "https://meet.nextphoton.com/session/cs013",
        status: "scheduled",
        topicsCovered: ["Photoelectric Effect", "Einstein's Equation", "Work Function"],
        enrolledStudents: 40,
        createdBy: "admin001",
    },
    {
        id: "cs014",
        title: "Algebra - Linear Equations",
        educatorId: "e004",
        educatorName: "Mr. Ramesh Kulkarni",
        classId: "batch_7th_cbse_01",
        batchName: "7th CBSE Regular",
        subject: "Mathematics",
        scheduledAt: "2024-03-19T09:30:00.000Z",
        durationMinutes: 60,
        meetingLink: "https://meet.nextphoton.com/session/cs014",
        recordingUrl: "https://recordings.nextphoton.com/cs014.mp4",
        status: "completed",
        topicsCovered: ["Simple Equations", "Transposition Method", "Word Problems"],
        learnersPresent: ["l008"],
        enrolledStudents: 30,
        notes: "28 students attended. Good understanding of basic concepts.",
        createdBy: "admin002",
    },
    {
        id: "cs015",
        title: "Coordination Chemistry - Isomerism",
        educatorId: "e002",
        educatorName: "Prof. Anand Iyer",
        classId: "batch_12th_cbse_01",
        batchName: "12th CBSE Science",
        subject: "Chemistry",
        scheduledAt: "2024-04-01T05:30:00.000Z",
        durationMinutes: 120,
        meetingLink: "https://meet.nextphoton.com/session/cs015",
        status: "scheduled",
        topicsCovered: ["Structural Isomerism", "Stereoisomerism", "Nomenclature"],
        enrolledStudents: 36,
        notes: "Advanced topic for 12th boards",
        createdBy: "admin001",
    },
    {
        id: "cs016",
        title: "JEE Main Mock Test Review",
        educatorId: "e001",
        educatorName: "Dr. Meera Sharma",
        classId: "batch_jee_2026_01",
        batchName: "JEE 2026 Advanced Batch",
        subject: "Physics",
        scheduledAt: "2024-03-24T03:30:00.000Z",
        durationMinutes: 90,
        meetingLink: "https://meet.nextphoton.com/session/cs016",
        status: "live",
        topicsCovered: ["Mock Test Analysis", "Common Mistakes", "Time Management"],
        enrolledStudents: 45,
        notes: "Currently in progress - reviewing last Sunday's mock test",
        createdBy: "admin001",
    },
    {
        id: "cs017",
        title: "NEET Biology Doubt Session",
        educatorId: "e003",
        educatorName: "Dr. Priya Nair",
        classId: "batch_neet_2025_01",
        batchName: "NEET 2025 Foundation",
        subject: "Biology",
        scheduledAt: "2024-03-24T06:00:00.000Z",
        durationMinutes: 60,
        meetingLink: "https://meet.nextphoton.com/session/cs017",
        status: "live",
        topicsCovered: ["Student Queries", "Difficult Topics", "Exam Tips"],
        enrolledStudents: 42,
        notes: "Live doubt clearing session in progress",
        createdBy: "admin002",
    }
];

export default classSessions;
  