// attendanceDummyData.ts

// Helper function to get dates relative to today
const getRelativeDate = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

// Use today's date and recent dates for the mock data
const TODAY = getRelativeDate(0);
const YESTERDAY = getRelativeDate(1);
const TWO_DAYS_AGO = getRelativeDate(2);
const THREE_DAYS_AGO = getRelativeDate(3);
const FOUR_DAYS_AGO = getRelativeDate(4);
const FIVE_DAYS_AGO = getRelativeDate(5);
const SIX_DAYS_AGO = getRelativeDate(6);
const WEEK_AGO = getRelativeDate(7);

export type AttendanceRecord = {
  id: string;
  sessionId: string;
  sessionName: string;
  sessionDate: string;
  learnerId: string;
  learnerName: string;
  learnerBatch?: string;
  educatorId: string;
  educatorName: string;
  subject: string;
  batchId: string;
  batchName: string;
  checkInTime: string | null;
  checkOutTime: string | null;
  duration: number; // in minutes
  status: "present" | "absent" | "late" | "excused" | "left-early";
  attendanceType: "on-time" | "late" | "very-late" | "excused" | "unexcused";
  lateReason?: string;
  excuseReason?: string;
  participationScore?: number; // 0-100
  cameraOn?: boolean;
  micUsed?: boolean;
  questionsAsked?: number;
  pollsAnswered?: number;
  assignmentSubmitted?: boolean;
  notes?: string;
  markedBy?: string;
  markedAt?: string;
  verifiedBy?: string;
  createdAt: string;
  updatedAt: string;
};

const attendanceRecords: AttendanceRecord[] = [
  // Today's attendance
  {
    id: "att001",
    sessionId: "cs003",
    sessionName: "Quadratic Equations - Problem Solving",
    sessionDate: TODAY,
    learnerId: "l001",
    learnerName: "Aarav Patel",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_10th_cbse_01",
    batchName: "10th CBSE Board Prep",
    checkInTime: "18:58",
    checkOutTime: "20:02",
    duration: 64,
    status: "present",
    attendanceType: "on-time",
    participationScore: 85,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 3,
    pollsAnswered: 2,
    notes: "Active participation, asked good questions about quadratic formula",
    markedBy: "system",
    markedAt: "2024-03-24T19:00:00Z",
    createdAt: "2024-03-24T19:00:00Z",
    updatedAt: "2024-03-24T20:15:00Z"
  },
  {
    id: "att002",
    sessionId: "cs003",
    sessionName: "Quadratic Equations - Problem Solving",
    sessionDate: TODAY,
    learnerId: "l002",
    learnerName: "Ishita Reddy",
    learnerBatch: "NEET 2025",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_10th_cbse_01",
    batchName: "10th CBSE Board Prep",
    checkInTime: "19:05",
    checkOutTime: "19:55",
    duration: 50,
    status: "late",
    attendanceType: "late",
    lateReason: "Technical issues with internet connection",
    participationScore: 70,
    cameraOn: true,
    micUsed: false,
    questionsAsked: 0,
    pollsAnswered: 2,
    notes: "Joined late due to connectivity issues but caught up well",
    markedBy: "system",
    markedAt: "2024-03-24T19:05:00Z",
    createdAt: "2024-03-24T19:05:00Z",
    updatedAt: "2024-03-24T20:15:00Z"
  },
  {
    id: "att003",
    sessionId: "cs003",
    sessionName: "Quadratic Equations - Problem Solving",
    sessionDate: TODAY,
    learnerId: "l003",
    learnerName: "Rohan Verma",
    learnerBatch: "10th CBSE",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_10th_cbse_01",
    batchName: "10th CBSE Board Prep",
    checkInTime: null,
    checkOutTime: null,
    duration: 0,
    status: "absent",
    attendanceType: "unexcused",
    participationScore: 0,
    cameraOn: false,
    micUsed: false,
    questionsAsked: 0,
    pollsAnswered: 0,
    notes: "No prior information about absence",
    markedBy: "e004",
    markedAt: "2024-03-24T20:15:00Z",
    createdAt: "2024-03-24T20:15:00Z",
    updatedAt: "2024-03-24T20:15:00Z"
  },
  {
    id: "att004",
    sessionId: "cs016",
    sessionName: "JEE Main Mock Test Review",
    sessionDate: TODAY,
    learnerId: "l001",
    learnerName: "Aarav Patel",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e001",
    educatorName: "Dr. Meera Sharma",
    subject: "Physics",
    batchId: "batch_jee_2026_01",
    batchName: "JEE 2026 Advanced Batch",
    checkInTime: "09:02",
    checkOutTime: "10:28",
    duration: 86,
    status: "present",
    attendanceType: "on-time",
    participationScore: 92,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 5,
    pollsAnswered: 4,
    notes: "Excellent engagement during mock test review",
    markedBy: "system",
    markedAt: "2024-03-24T09:02:00Z",
    createdAt: "2024-03-24T09:02:00Z",
    updatedAt: "2024-03-24T10:30:00Z"
  },
  {
    id: "att005",
    sessionId: "cs017",
    sessionName: "NEET Biology Doubt Session",
    sessionDate: TODAY,
    learnerId: "l002",
    learnerName: "Ishita Reddy",
    learnerBatch: "NEET 2025",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "11:30",
    checkOutTime: "12:25",
    duration: 55,
    status: "present",
    attendanceType: "on-time",
    participationScore: 88,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 4,
    pollsAnswered: 3,
    notes: "Asked detailed questions about respiratory system",
    markedBy: "system",
    markedAt: "2024-03-24T11:30:00Z",
    createdAt: "2024-03-24T11:30:00Z",
    updatedAt: "2024-03-24T12:30:00Z"
  },
  {
    id: "att006",
    sessionId: "cs017",
    sessionName: "NEET Biology Doubt Session",
    sessionDate: TODAY,
    learnerId: "l006",
    learnerName: "Simran Kaur",
    learnerBatch: "NEET 2025",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "11:32",
    checkOutTime: "12:25",
    duration: 53,
    status: "present",
    attendanceType: "on-time",
    participationScore: 85,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 3,
    notes: "Good participation in doubt clearing session",
    markedBy: "system",
    markedAt: "2024-03-24T11:32:00Z",
    createdAt: "2024-03-24T11:32:00Z",
    updatedAt: "2024-03-24T12:30:00Z"
  },

  // Yesterday's attendance (March 23, 2024)
  {
    id: "att007",
    sessionId: "cs005",
    sessionName: "Essay Writing Skills",
    sessionDate: YESTERDAY,
    learnerId: "l004",
    learnerName: "Ananya Singh",
    learnerBatch: "8th CBSE",
    educatorId: "e006",
    educatorName: "Ms. Kavita Menon",
    subject: "English",
    batchId: "batch_8th_cbse_01",
    batchName: "8th CBSE Regular",
    checkInTime: "14:57",
    checkOutTime: "16:32",
    duration: 95,
    status: "present",
    attendanceType: "on-time",
    participationScore: 92,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 3,
    assignmentSubmitted: true,
    notes: "Excellent engagement, submitted essay outline during class",
    markedBy: "system",
    markedAt: "2024-03-23T15:00:00Z",
    createdAt: "2024-03-23T15:00:00Z",
    updatedAt: "2024-03-23T17:00:00Z"
  },
  {
    id: "att008",
    sessionId: "cs005",
    sessionName: "Essay Writing Skills",
    sessionDate: YESTERDAY,
    learnerId: "l007",
    learnerName: "Aditya Rao",
    learnerBatch: "9th CBSE",
    educatorId: "e006",
    educatorName: "Ms. Kavita Menon",
    subject: "English",
    batchId: "batch_8th_cbse_01",
    batchName: "8th CBSE Regular",
    checkInTime: "15:10",
    checkOutTime: "16:30",
    duration: 80,
    status: "late",
    attendanceType: "late",
    lateReason: "Previous class extended",
    participationScore: 75,
    cameraOn: false,
    micUsed: true,
    questionsAsked: 1,
    pollsAnswered: 2,
    notes: "Camera issues but participated via voice",
    markedBy: "system",
    markedAt: "2024-03-23T15:10:00Z",
    createdAt: "2024-03-23T15:10:00Z",
    updatedAt: "2024-03-23T17:00:00Z"
  },
  {
    id: "att009",
    sessionId: "cs005",
    sessionName: "Essay Writing Skills",
    sessionDate: YESTERDAY,
    learnerId: "l008",
    learnerName: "Priya Sharma",
    learnerBatch: "7th CBSE",
    educatorId: "e006",
    educatorName: "Ms. Kavita Menon",
    subject: "English",
    batchId: "batch_8th_cbse_01",
    batchName: "8th CBSE Regular",
    checkInTime: "14:58",
    checkOutTime: "16:30",
    duration: 92,
    status: "present",
    attendanceType: "on-time",
    participationScore: 90,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 3,
    pollsAnswered: 3,
    assignmentSubmitted: true,
    notes: "Very active participant, helped other students",
    markedBy: "system",
    markedAt: "2024-03-23T15:00:00Z",
    createdAt: "2024-03-23T15:00:00Z",
    updatedAt: "2024-03-23T17:00:00Z"
  },

  // March 22, 2024
  {
    id: "att010",
    sessionId: "cs008",
    sessionName: "Indian Independence Movement",
    sessionDate: TWO_DAYS_AGO,
    learnerId: "l005",
    learnerName: "Arjun Malhotra",
    learnerBatch: "12th Humanities",
    educatorId: "e005",
    educatorName: "Prof. Sanjay Gupta",
    subject: "History",
    batchId: "batch_12th_humanities_01",
    batchName: "12th Humanities",
    checkInTime: "11:02",
    checkOutTime: "12:28",
    duration: 86,
    status: "present",
    attendanceType: "on-time",
    participationScore: 78,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 1,
    pollsAnswered: 1,
    notes: "Good participation in discussion about partition",
    markedBy: "system",
    markedAt: "2024-03-22T11:02:00Z",
    createdAt: "2024-03-22T11:02:00Z",
    updatedAt: "2024-03-22T13:00:00Z"
  },

  // March 21, 2024
  {
    id: "att011",
    sessionId: "cs010",
    sessionName: "Life Processes - Nutrition",
    sessionDate: THREE_DAYS_AGO,
    learnerId: "l003",
    learnerName: "Rohan Verma",
    learnerBatch: "10th CBSE",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_10th_cbse_01",
    batchName: "10th CBSE Board Prep",
    checkInTime: "17:00",
    checkOutTime: "18:02",
    duration: 62,
    status: "present",
    attendanceType: "on-time",
    participationScore: 82,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 2,
    notes: "Good understanding of digestive system",
    markedBy: "system",
    markedAt: "2024-03-21T17:00:00Z",
    createdAt: "2024-03-21T17:00:00Z",
    updatedAt: "2024-03-21T18:30:00Z"
  },
  {
    id: "att012",
    sessionId: "cs010",
    sessionName: "Life Processes - Nutrition",
    sessionDate: THREE_DAYS_AGO,
    learnerId: "l006",
    learnerName: "Simran Kaur",
    learnerBatch: "10th CBSE",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_10th_cbse_01",
    batchName: "10th CBSE Board Prep",
    checkInTime: "17:00",
    checkOutTime: "18:05",
    duration: 65,
    status: "present",
    attendanceType: "on-time",
    participationScore: 88,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 4,
    pollsAnswered: 2,
    notes: "Very active, asked detailed questions about digestive enzymes",
    markedBy: "system",
    markedAt: "2024-03-21T17:00:00Z",
    createdAt: "2024-03-21T17:00:00Z",
    updatedAt: "2024-03-21T18:30:00Z"
  },

  // March 20, 2024
  {
    id: "att013",
    sessionId: "cs012",
    sessionName: "Physical Geography - Climate and Weather",
    sessionDate: FOUR_DAYS_AGO,
    learnerId: "l007",
    learnerName: "Aditya Rao",
    learnerBatch: "9th CBSE",
    educatorId: "e008",
    educatorName: "Ms. Neha Singh",
    subject: "Geography",
    batchId: "batch_9th_cbse_01",
    batchName: "9th CBSE Regular",
    checkInTime: "14:10",
    checkOutTime: "15:30",
    duration: 80,
    status: "late",
    attendanceType: "late",
    lateReason: "Previous class extended",
    participationScore: 75,
    cameraOn: false,
    micUsed: true,
    questionsAsked: 1,
    pollsAnswered: 1,
    notes: "Camera issues, but participated via voice",
    markedBy: "system",
    markedAt: "2024-03-20T14:10:00Z",
    createdAt: "2024-03-20T14:10:00Z",
    updatedAt: "2024-03-20T16:00:00Z"
  },

  // March 19, 2024
  {
    id: "att014",
    sessionId: "cs014",
    sessionName: "Algebra - Linear Equations",
    sessionDate: FIVE_DAYS_AGO,
    learnerId: "l008",
    learnerName: "Priya Sharma",
    learnerBatch: "7th CBSE",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_7th_cbse_01",
    batchName: "7th CBSE Regular",
    checkInTime: "14:58",
    checkOutTime: "16:02",
    duration: 64,
    status: "present",
    attendanceType: "on-time",
    participationScore: 90,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 3,
    assignmentSubmitted: true,
    notes: "Solved problems on board, very engaged",
    markedBy: "system",
    markedAt: "2024-03-19T15:00:00Z",
    createdAt: "2024-03-19T15:00:00Z",
    updatedAt: "2024-03-19T16:30:00Z"
  },

  // March 18, 2024 - Multiple sessions
  {
    id: "att015",
    sessionId: "cs001",
    sessionName: "Mechanics - Newton's Laws Advanced Problems",
    sessionDate: SIX_DAYS_AGO,
    learnerId: "l001",
    learnerName: "Aarav Patel",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e001",
    educatorName: "Dr. Meera Sharma",
    subject: "Physics",
    batchId: "batch_jee_2026_01",
    batchName: "JEE 2026 Advanced Batch",
    checkInTime: "16:00",
    checkOutTime: "18:05",
    duration: 125,
    status: "present",
    attendanceType: "on-time",
    participationScore: 95,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 5,
    pollsAnswered: 4,
    notes: "Excellent problem-solving skills demonstrated",
    markedBy: "system",
    markedAt: "2024-03-18T16:00:00Z",
    createdAt: "2024-03-18T16:00:00Z",
    updatedAt: "2024-03-18T18:30:00Z"
  },
  {
    id: "att016",
    sessionId: "cs001",
    sessionName: "Mechanics - Newton's Laws Advanced Problems",
    sessionDate: SIX_DAYS_AGO,
    learnerId: "l009",
    learnerName: "Rahul Kumar",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e001",
    educatorName: "Dr. Meera Sharma",
    subject: "Physics",
    batchId: "batch_jee_2026_01",
    batchName: "JEE 2026 Advanced Batch",
    checkInTime: null,
    checkOutTime: null,
    duration: 0,
    status: "excused",
    attendanceType: "excused",
    excuseReason: "Medical emergency - certificate provided",
    participationScore: 0,
    cameraOn: false,
    micUsed: false,
    questionsAsked: 0,
    pollsAnswered: 0,
    notes: "Prior intimation given, medical certificate provided",
    markedBy: "e001",
    markedAt: "2024-03-18T18:30:00Z",
    verifiedBy: "admin001",
    createdAt: "2024-03-18T18:30:00Z",
    updatedAt: "2024-03-18T18:30:00Z"
  },

  // March 17, 2024
  {
    id: "att017",
    sessionId: "cs002",
    sessionName: "Organic Chemistry - Reaction Mechanisms",
    sessionDate: WEEK_AGO,
    learnerId: "l002",
    learnerName: "Ishita Reddy",
    learnerBatch: "NEET 2025",
    educatorId: "e002",
    educatorName: "Prof. Anand Iyer",
    subject: "Chemistry",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "14:00",
    checkOutTime: "16:00",
    duration: 120,
    status: "present",
    attendanceType: "on-time",
    participationScore: 87,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 3,
    pollsAnswered: 3,
    notes: "Good understanding of reaction mechanisms",
    markedBy: "system",
    markedAt: "2024-03-17T14:00:00Z",
    createdAt: "2024-03-17T14:00:00Z",
    updatedAt: "2024-03-17T16:30:00Z"
  },
  {
    id: "att018",
    sessionId: "cs002",
    sessionName: "Organic Chemistry - Reaction Mechanisms",
    sessionDate: WEEK_AGO,
    learnerId: "l006",
    learnerName: "Simran Kaur",
    learnerBatch: "NEET 2025",
    educatorId: "e002",
    educatorName: "Prof. Anand Iyer",
    subject: "Chemistry",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "14:15",
    checkOutTime: "16:00",
    duration: 105,
    status: "late",
    attendanceType: "late",
    lateReason: "Power outage at home",
    participationScore: 72,
    cameraOn: false,
    micUsed: true,
    questionsAsked: 1,
    pollsAnswered: 2,
    notes: "Joined via mobile due to power issues",
    markedBy: "system",
    markedAt: "2024-03-17T14:15:00Z",
    createdAt: "2024-03-17T14:15:00Z",
    updatedAt: "2024-03-17T16:30:00Z"
  },

  // 8 days ago
  {
    id: "att019",
    sessionId: "cs004",
    sessionName: "Human Physiology - Respiratory System",
    sessionDate: getRelativeDate(8),
    learnerId: "l002",
    learnerName: "Ishita Reddy",
    learnerBatch: "NEET 2025",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "10:00",
    checkOutTime: "12:00",
    duration: 120,
    status: "present",
    attendanceType: "on-time",
    participationScore: 91,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 4,
    pollsAnswered: 5,
    notes: "Excellent diagram work, very attentive",
    markedBy: "system",
    markedAt: "2024-03-16T10:00:00Z",
    createdAt: "2024-03-16T10:00:00Z",
    updatedAt: "2024-03-16T12:30:00Z"
  },
  {
    id: "att020",
    sessionId: "cs004",
    sessionName: "Human Physiology - Respiratory System",
    sessionDate: getRelativeDate(8),
    learnerId: "l006",
    learnerName: "Simran Kaur",
    learnerBatch: "NEET 2025",
    educatorId: "e003",
    educatorName: "Dr. Priya Nair",
    subject: "Biology",
    batchId: "batch_neet_2025_01",
    batchName: "NEET 2025 Foundation",
    checkInTime: "10:00",
    checkOutTime: "11:30",
    duration: 90,
    status: "left-early",
    attendanceType: "on-time",
    excuseReason: "Had to leave for another commitment",
    participationScore: 80,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 4,
    notes: "Had to leave early for family event",
    markedBy: "system",
    markedAt: "2024-03-16T10:00:00Z",
    createdAt: "2024-03-16T10:00:00Z",
    updatedAt: "2024-03-16T12:30:00Z"
  },

  // March 15, 2024
  {
    id: "att021",
    sessionId: "cs007",
    sessionName: "Calculus - Integration Techniques",
    sessionDate: getRelativeDate(9),
    learnerId: "l001",
    learnerName: "Aarav Patel",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_jee_2026_01",
    batchName: "JEE 2026 Advanced Batch",
    checkInTime: "18:00",
    checkOutTime: "20:00",
    duration: 120,
    status: "present",
    attendanceType: "on-time",
    participationScore: 93,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 3,
    pollsAnswered: 4,
    notes: "Solved advanced integration problems correctly",
    markedBy: "system",
    markedAt: "2024-03-15T18:00:00Z",
    createdAt: "2024-03-15T18:00:00Z",
    updatedAt: "2024-03-15T20:30:00Z"
  },
  {
    id: "att022",
    sessionId: "cs007",
    sessionName: "Calculus - Integration Techniques",
    sessionDate: getRelativeDate(9),
    learnerId: "l009",
    learnerName: "Rahul Kumar",
    learnerBatch: "JEE 2026 Advanced",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_jee_2026_01",
    batchName: "JEE 2026 Advanced Batch",
    checkInTime: "18:05",
    checkOutTime: "20:00",
    duration: 115,
    status: "late",
    attendanceType: "late",
    lateReason: "Traffic delay",
    participationScore: 85,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 2,
    pollsAnswered: 3,
    notes: "Good effort, needs practice with substitution method",
    markedBy: "system",
    markedAt: "2024-03-15T18:05:00Z",
    createdAt: "2024-03-15T18:05:00Z",
    updatedAt: "2024-03-15T20:30:00Z"
  },

  // Week summary data for other learners
  {
    id: "att023",
    sessionId: "cs011",
    sessionName: "Python Programming - Functions and Modules",
    sessionDate: getRelativeDate(11),
    learnerId: "l003",
    learnerName: "Rohan Verma",
    learnerBatch: "11th CS",
    educatorId: "e007",
    educatorName: "Mr. Arun Kumar",
    subject: "Computer Science",
    batchId: "batch_11th_cs_01",
    batchName: "11th Computer Science",
    checkInTime: "10:00",
    checkOutTime: "12:00",
    duration: 120,
    status: "present",
    attendanceType: "on-time",
    participationScore: 94,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 4,
    pollsAnswered: 3,
    assignmentSubmitted: true,
    notes: "Excellent coding skills, completed all exercises",
    markedBy: "system",
    markedAt: "2024-03-13T10:00:00Z",
    createdAt: "2024-03-13T10:00:00Z",
    updatedAt: "2024-03-13T12:30:00Z"
  },
  {
    id: "att024",
    sessionId: "special_doubt_01",
    sessionName: "Special Doubt Session - Mathematics",
    sessionDate: getRelativeDate(12),
    learnerId: "l004",
    learnerName: "Ananya Singh",
    learnerBatch: "8th CBSE",
    educatorId: "e004",
    educatorName: "Mr. Ramesh Kulkarni",
    subject: "Mathematics",
    batchId: "batch_8th_cbse_01",
    batchName: "8th CBSE Regular",
    checkInTime: "15:00",
    checkOutTime: "15:45",
    duration: 45,
    status: "present",
    attendanceType: "on-time",
    participationScore: 88,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 6,
    pollsAnswered: 0,
    notes: "Focused doubt clearing session on algebra",
    markedBy: "system",
    markedAt: "2024-03-12T15:00:00Z",
    createdAt: "2024-03-12T15:00:00Z",
    updatedAt: "2024-03-12T16:00:00Z"
  },
  {
    id: "att025",
    sessionId: "special_practice_01",
    sessionName: "Extra Practice Session - History",
    sessionDate: getRelativeDate(13),
    learnerId: "l005",
    learnerName: "Arjun Malhotra",
    learnerBatch: "12th Humanities",
    educatorId: "e005",
    educatorName: "Prof. Sanjay Gupta",
    subject: "History",
    batchId: "batch_12th_humanities_01",
    batchName: "12th Humanities",
    checkInTime: "16:00",
    checkOutTime: "17:30",
    duration: 90,
    status: "present",
    attendanceType: "on-time",
    participationScore: 82,
    cameraOn: true,
    micUsed: true,
    questionsAsked: 3,
    pollsAnswered: 2,
    notes: "Good participation in group discussion",
    markedBy: "system",
    markedAt: "2024-03-11T16:00:00Z",
    createdAt: "2024-03-11T16:00:00Z",
    updatedAt: "2024-03-11T17:45:00Z"
  }
];

// Helper function to get attendance summary
export const getAttendanceSummary = (learnerId?: string) => {
  const relevantRecords = learnerId
    ? attendanceRecords.filter(r => r.learnerId === learnerId)
    : attendanceRecords;

  const today = new Date().toISOString().split('T')[0];
  const todayRecords = relevantRecords.filter(r => r.sessionDate === today);

  const presentToday = todayRecords.filter(r => r.status === "present" || r.status === "late").length;
  const absentToday = todayRecords.filter(r => r.status === "absent").length;
  const excusedToday = todayRecords.filter(r => r.status === "excused").length;

  const totalPresent = relevantRecords.filter(r => r.status === "present" || r.status === "late").length;
  const totalAbsent = relevantRecords.filter(r => r.status === "absent").length;
  const totalExcused = relevantRecords.filter(r => r.status === "excused").length;

  const attendanceRate = relevantRecords.length > 0
    ? Math.round((totalPresent / relevantRecords.length) * 100)
    : 0;

  return {
    presentToday,
    absentToday,
    excusedToday,
    totalPresent,
    totalAbsent,
    totalExcused,
    attendanceRate,
    totalRecords: relevantRecords.length
  };
};

// Get learner-specific attendance
export const getLearnerAttendance = (learnerId: string) => {
  return attendanceRecords.filter(record => record.learnerId === learnerId);
};

// Get session-specific attendance
export const getSessionAttendance = (sessionId: string) => {
  return attendanceRecords.filter(record => record.sessionId === sessionId);
};

// Get today's attendance
export const getTodayAttendance = () => {
  const today = getRelativeDate(0); // Using the same helper function
  return attendanceRecords.filter(record => record.sessionDate === today);
};

export default attendanceRecords;